# Generated by Django 4.1.3 on 2022-12-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aseguradora',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='dni',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rodado',
            name='km',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rodado',
            name='precio',
            field=models.CharField(max_length=20),
        ),
    ]
