# Generated by Django 4.1.3 on 2022-12-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_aseguradora_telefono_alter_comprador_dni_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aseguradora',
        ),
    ]
