# Generated by Django 4.1.3 on 2022-12-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_delete_aseguradora'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comprador',
            new_name='Empleados',
        ),
        migrations.DeleteModel(
            name='Rodado',
        ),
    ]
