# Generated by Django 4.1.3 on 2022-12-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_rename_comprador_empleados_delete_rodado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleados',
        ),
    ]
