# Generated by Django 4.1.3 on 2022-12-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rodado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('km', models.IntegerField()),
                ('año', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('patente', models.CharField(max_length=20)),
                ('vtv_hecha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('dni', models.IntegerField()),
                ('domicilio', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=20)),
                ('celular', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
