# Generated by Django 4.1.3 on 2022-12-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodado',
            name='km',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rodado',
            name='precio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
