# Generated by Django 4.1.3 on 2022-12-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_alter_rodado_km_alter_rodado_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='dni',
            field=models.CharField(max_length=20),
        ),
    ]
