# Generated by Django 4.1.3 on 2022-12-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_alter_vendedor_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('celular', models.IntegerField()),
                ('poliza', models.IntegerField()),
                ('domicilio', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=20)),
            ],
        ),
    ]
