# Generated by Django 4.1.3 on 2022-12-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escritor', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=350)),
            ],
        ),
        migrations.RemoveField(
            model_name='aseguradora',
            name='localidad',
        ),
    ]
