# Generated by Django 4.1.3 on 2022-12-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0007_mensajes_remove_aseguradora_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodado',
            name='nombre_apellido_vendedor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rodado',
            name='telefono',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
