#FALTA ESCRIBIR ACA PARA QUE AL ESCRIBIR DATOS EN EL FORMULARIO DE AUTOMOVILES (COMPRA) SE GUARDEN CORRECTAMENTE EN LA BASE DE DATOS.

#LUEGO HAY QUE CREAR OTROS TEMPLATES QUE NO LLEGUÉ A HACERLOS, SOLO HICE EL DE DELETE, DETAIL, Y CREAR, FALTA EL RESTO. MIRAR FINAL DE CLASE 1 AVANZADO.